### ISSUE TITLE
Can't pipe() to stream

### ISSUE THREAD

**Issue by feross** [Raynos/console-stream#1]
I think that `pipe()`ing doesn't work because you didn't implement a pipe method. Why not just subclass from the Writable class and get that for free?

**Comment by Raynos** [comment]
A writable stream does not have `.pipe()` Only readable streams do.

You do `x.pipe(ConsoleStream())`

**Comment by feross** [comment]
Do'h, you're right about `.pipe()`, my bad.

**Comment by feross** [comment]
I think the thing I was calling `pipe` on wasn't actually a readable stream...
